[package]
name = "gamer-monitor"
version = "1.2.1"
edition = "2021"
authors = ["Felipe Miguel Nery Lunkes, Jo√£o Paulo Fernandes Salviano"]

[dependencies]
gtk4 = "0.9"
glib = "0.20"
regex = "1.11"
once_cell = "1.21.3"

[[bin]]
name = "gamer-monitor"
path = "src/main.rs"
