[package]
name = "gamer-monitor"
version = "1.2.2"
edition = "2024"
authors = ["Felipe Miguel Nery Lunkes, Jo√£o Paulo Fernandes Salviano"]

[dependencies]
gtk4 = "0.11.0"
glib = "0.22.0"
regex = "1.11"
once_cell = "1.21.3"

[[bin]]
name = "gamer-monitor"
path = "src/main.rs"
